name: Next App Template Analytics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Get the analytics every hour

jobs:
  get_analytics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Script to Get Analytics
      run: python .github/scripts/get_analytics.py
      env:
        ANALYTICS_ENDPOINT: 'https://makenext.app/api/analytics' # Change this to your production server URL
