name: Make Next App Misc Jobs

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  get_analytics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Script to Send Request to Run Misc Jobs
      run: python .github/scripts/run_misc.py
      env:
        MISC_ENDPOINT: 'https://makenext.app/api/misc' # Change this to your production server URL
